import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import 'remixicon/fonts/remixicon.css'
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"], // 400 = normal, 700 = bold
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${poppins.className} antialiased`}
      >
        <Navbar/>
        <div className="container mx-auto px-10 sm:px-9 md:pl-36 lg:pl-40 xl:pl-60 pt-7">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
